from api.routers.account import account_router
from api.routers.events import events_router
from api.routers.invites import invites_router
from api.routers.organization import organization_router
from api.routers.permissions import permissions_router
from api.routers.registrations import registrations_router
from api.routers.room_groups import room_groups_router
from api.routers.rooms import rooms_router
from api.routers.units import units_router
from api.routers.user_groups import user_groups_router
from api.routers.users import users_router
from api.routers.bildings import buildings_router
